<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-IETT_APP.WebMVC-faa2b814-4fac-4885-ade3-b40dd1a5bd2a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="9.0.9" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.9" />
    <PackageReference Include="Microsoft.Identity.Web" Version="3.14.1" />
    <PackageReference Include="Microsoft.Identity.Web.UI" Version="3.14.1" />
    <PackageReference Include="Microsoft.Identity.Web.DownstreamApi" Version="3.14.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IETT_APP.Applicaton\IETT_APP.Applicaton.csproj" />
    <ProjectReference Include="..\IETT_APP.Domain\IETT_APP.Domain.csproj" />
    <ProjectReference Include="..\IETT_APP.Infrastructure\IETT_APP.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Data\" />
    <Folder Include="Areas\Chief\Data\" />
    <Folder Include="Areas\Chief\Models\" />
    <Folder Include="Areas\Driver\Data\" />
    <Folder Include="Areas\Driver\Models\" />
    <Folder Include="Areas\Planner\Data\" />
    <Folder Include="wwwroot\assets\css\alt\" />
    <Folder Include="wwwroot\assets\js\adminlte_3.2.0\pages\" />
    <Folder Include="wwwroot\assets\lib\bootstrap\dist\css\" />
    <Folder Include="wwwroot\assets\lib\bootstrap\dist\js\" />
    <Folder Include="wwwroot\assets\lib\jquery-validation-unobtrusive\" />
    <Folder Include="wwwroot\assets\lib\jquery-validation\dist\" />
    <Folder Include="wwwroot\assets\lib\jquery\dist\" />
    <Folder Include="wwwroot\assets\plugins\bootstrap-colorpicker\css\" />
    <Folder Include="wwwroot\assets\plugins\bootstrap-colorpicker\js\" />
    <Folder Include="wwwroot\assets\plugins\bootstrap-slider\css\" />
    <Folder Include="wwwroot\assets\plugins\bootstrap-switch\css\bootstrap2\" />
    <Folder Include="wwwroot\assets\plugins\bootstrap-switch\css\bootstrap3\" />
    <Folder Include="wwwroot\assets\plugins\bootstrap-switch\js\" />
    <Folder Include="wwwroot\assets\plugins\bootstrap4-duallistbox\" />
    <Folder Include="wwwroot\assets\plugins\bootstrap\js\" />
    <Folder Include="wwwroot\assets\plugins\bs-custom-file-input\" />
    <Folder Include="wwwroot\assets\plugins\bs-stepper\css\" />
    <Folder Include="wwwroot\assets\plugins\bs-stepper\js\" />
    <Folder Include="wwwroot\assets\plugins\chart.js\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\addon\comment\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\addon\dialog\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\addon\display\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\addon\edit\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\addon\fold\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\addon\hint\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\addon\lint\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\addon\merge\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\addon\mode\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\addon\runmode\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\addon\scroll\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\addon\search\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\addon\selection\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\addon\tern\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\addon\wrap\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\keymap\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\apl\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\asciiarmor\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\asn.1\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\asterisk\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\brainfuck\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\clike\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\clojure\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\cmake\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\cobol\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\coffeescript\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\commonlisp\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\crystal\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\css\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\cypher\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\dart\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\diff\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\django\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\dockerfile\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\dtd\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\dylan\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\d\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\ebnf\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\ecl\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\eiffel\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\elm\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\erlang\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\factor\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\fcl\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\forth\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\fortran\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\gas\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\gfm\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\gherkin\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\go\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\groovy\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\haml\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\handlebars\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\haskell-literate\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\haskell\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\haxe\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\htmlembedded\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\htmlmixed\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\http\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\idl\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\javascript\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\jinja2\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\jsx\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\julia\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\livescript\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\lua\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\markdown\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\mathematica\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\mbox\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\mirc\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\mllike\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\modelica\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\mscgen\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\mumps\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\nginx\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\nsis\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\ntriples\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\octave\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\oz\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\pascal\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\pegjs\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\perl\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\php\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\pig\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\powershell\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\properties\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\protobuf\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\pug\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\puppet\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\python\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\q\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\rpm\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\rst\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\ruby\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\rust\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\r\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\sass\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\sas\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\scheme\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\shell\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\sieve\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\slim\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\smalltalk\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\smarty\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\solr\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\soy\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\sparql\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\spreadsheet\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\sql\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\stex\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\stylus\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\swift\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\tcl\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\textile\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\tiddlywiki\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\tiki\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\toml\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\tornado\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\troff\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\ttcn-cfg\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\ttcn\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\turtle\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\twig\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\vbscript\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\vb\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\velocity\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\verilog\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\vhdl\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\vue\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\wast\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\webidl\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\xml\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\xquery\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\yacas\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\yaml-frontmatter\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\yaml\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\mode\z80\" />
    <Folder Include="wwwroot\assets\plugins\codemirror\theme\" />
    <Folder Include="wwwroot\assets\plugins\datatables-autofill\css\" />
    <Folder Include="wwwroot\assets\plugins\datatables-autofill\js\" />
    <Folder Include="wwwroot\assets\plugins\datatables-bs4\css\" />
    <Folder Include="wwwroot\assets\plugins\datatables-bs4\js\" />
    <Folder Include="wwwroot\assets\plugins\datatables-buttons\css\" />
    <Folder Include="wwwroot\assets\plugins\datatables-buttons\js\" />
    <Folder Include="wwwroot\assets\plugins\datatables-colreorder\css\" />
    <Folder Include="wwwroot\assets\plugins\datatables-colreorder\js\" />
    <Folder Include="wwwroot\assets\plugins\datatables-fixedcolumns\css\" />
    <Folder Include="wwwroot\assets\plugins\datatables-fixedcolumns\js\" />
    <Folder Include="wwwroot\assets\plugins\datatables-fixedheader\css\" />
    <Folder Include="wwwroot\assets\plugins\datatables-fixedheader\js\" />
    <Folder Include="wwwroot\assets\plugins\datatables-keytable\css\" />
    <Folder Include="wwwroot\assets\plugins\datatables-keytable\js\" />
    <Folder Include="wwwroot\assets\plugins\datatables-responsive\css\" />
    <Folder Include="wwwroot\assets\plugins\datatables-responsive\js\" />
    <Folder Include="wwwroot\assets\plugins\datatables-rowgroup\css\" />
    <Folder Include="wwwroot\assets\plugins\datatables-rowgroup\js\" />
    <Folder Include="wwwroot\assets\plugins\datatables-rowreorder\css\" />
    <Folder Include="wwwroot\assets\plugins\datatables-rowreorder\js\" />
    <Folder Include="wwwroot\assets\plugins\datatables-scroller\css\" />
    <Folder Include="wwwroot\assets\plugins\datatables-scroller\js\" />
    <Folder Include="wwwroot\assets\plugins\datatables-searchbuilder\css\" />
    <Folder Include="wwwroot\assets\plugins\datatables-searchbuilder\js\" />
    <Folder Include="wwwroot\assets\plugins\datatables-searchpanes\css\" />
    <Folder Include="wwwroot\assets\plugins\datatables-searchpanes\js\" />
    <Folder Include="wwwroot\assets\plugins\datatables-select\css\" />
    <Folder Include="wwwroot\assets\plugins\datatables-select\js\" />
    <Folder Include="wwwroot\assets\plugins\datatables\" />
    <Folder Include="wwwroot\assets\plugins\daterangepicker\" />
    <Folder Include="wwwroot\assets\plugins\dropzone\min\" />
    <Folder Include="wwwroot\assets\plugins\ekko-lightbox\" />
    <Folder Include="wwwroot\assets\plugins\fastclick\" />
    <Folder Include="wwwroot\assets\plugins\filterizr\" />
    <Folder Include="wwwroot\assets\plugins\flag-icon-css\css\" />
    <Folder Include="wwwroot\assets\plugins\flag-icon-css\flags\1x1\" />
    <Folder Include="wwwroot\assets\plugins\flag-icon-css\flags\4x3\" />
    <Folder Include="wwwroot\assets\plugins\flot\plugins\" />
    <Folder Include="wwwroot\assets\plugins\fontawesome-free\css\" />
    <Folder Include="wwwroot\assets\plugins\fontawesome-free\webfonts\" />
    <Folder Include="wwwroot\assets\plugins\fullcalendar\locales\" />
    <Folder Include="wwwroot\assets\plugins\icheck-bootstrap\" />
    <Folder Include="wwwroot\assets\plugins\inputmask\" />
    <Folder Include="wwwroot\assets\plugins\ion-rangeslider\css\" />
    <Folder Include="wwwroot\assets\plugins\ion-rangeslider\js\" />
    <Folder Include="wwwroot\assets\plugins\jquery-knob\" />
    <Folder Include="wwwroot\assets\plugins\jquery-mapael\maps\" />
    <Folder Include="wwwroot\assets\plugins\jquery-mousewheel\" />
    <Folder Include="wwwroot\assets\plugins\jquery-ui\images\" />
    <Folder Include="wwwroot\assets\plugins\jquery-validation\localization\" />
    <Folder Include="wwwroot\assets\plugins\jquery\" />
    <Folder Include="wwwroot\assets\plugins\jqvmap\maps\continents\" />
    <Folder Include="wwwroot\assets\plugins\jsgrid\demos\" />
    <Folder Include="wwwroot\assets\plugins\jsgrid\i18n\" />
    <Folder Include="wwwroot\assets\plugins\jszip\" />
    <Folder Include="wwwroot\assets\plugins\moment\locale\" />
    <Folder Include="wwwroot\assets\plugins\overlayScrollbars\css\" />
    <Folder Include="wwwroot\assets\plugins\overlayScrollbars\js\" />
    <Folder Include="wwwroot\assets\plugins\pace-progress\themes\black\" />
    <Folder Include="wwwroot\assets\plugins\pace-progress\themes\blue\" />
    <Folder Include="wwwroot\assets\plugins\pace-progress\themes\green\" />
    <Folder Include="wwwroot\assets\plugins\pace-progress\themes\orange\" />
    <Folder Include="wwwroot\assets\plugins\pace-progress\themes\pink\" />
    <Folder Include="wwwroot\assets\plugins\pace-progress\themes\purple\" />
    <Folder Include="wwwroot\assets\plugins\pace-progress\themes\red\" />
    <Folder Include="wwwroot\assets\plugins\pace-progress\themes\silver\" />
    <Folder Include="wwwroot\assets\plugins\pace-progress\themes\white\" />
    <Folder Include="wwwroot\assets\plugins\pace-progress\themes\yellow\" />
    <Folder Include="wwwroot\assets\plugins\pdfmake\" />
    <Folder Include="wwwroot\assets\plugins\popper\esm\" />
    <Folder Include="wwwroot\assets\plugins\popper\umd\" />
    <Folder Include="wwwroot\assets\plugins\raphael\" />
    <Folder Include="wwwroot\assets\plugins\select2-bootstrap4-theme\" />
    <Folder Include="wwwroot\assets\plugins\select2\css\" />
    <Folder Include="wwwroot\assets\plugins\select2\js\i18n\" />
    <Folder Include="wwwroot\assets\plugins\sparklines\" />
    <Folder Include="wwwroot\assets\plugins\summernote\font\" />
    <Folder Include="wwwroot\assets\plugins\summernote\lang\" />
    <Folder Include="wwwroot\assets\plugins\summernote\plugin\databasic\" />
    <Folder Include="wwwroot\assets\plugins\summernote\plugin\hello\" />
    <Folder Include="wwwroot\assets\plugins\summernote\plugin\specialchars\" />
    <Folder Include="wwwroot\assets\plugins\sweetalert2-theme-bootstrap-4\" />
    <Folder Include="wwwroot\assets\plugins\sweetalert2\" />
    <Folder Include="wwwroot\assets\plugins\tempusdominus-bootstrap-4\css\" />
    <Folder Include="wwwroot\assets\plugins\tempusdominus-bootstrap-4\js\" />
    <Folder Include="wwwroot\assets\plugins\toastr\" />
    <Folder Include="wwwroot\assets\plugins\uplot\" />
  </ItemGroup>

</Project>
